[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230E75649B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a812b33c-23d4-4b60-b6bd-e219b8cabe50/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230E7564B30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a812b33c-23d4-4b60-b6bd-e219b8cabe50/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230E7564890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a812b33c-23d4-4b60-b6bd-e219b8cabe50/element